services:
  - type: web
    name: e-invoice-travel-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: "E-Invoice Travel Agency API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
